// Code generated by go-swagger; DO NOT EDIT.

package business

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/mercadofarma/services/models"
)

// SignUpAdminNoContentCode is the HTTP code returned for type SignUpAdminNoContent
const SignUpAdminNoContentCode int = 204

/*
SignUpAdminNoContent No content

swagger:response signUpAdminNoContent
*/
type SignUpAdminNoContent struct {
}

// NewSignUpAdminNoContent creates SignUpAdminNoContent with default headers values
func NewSignUpAdminNoContent() *SignUpAdminNoContent {

	return &SignUpAdminNoContent{}
}

// WriteResponse to the client
func (o *SignUpAdminNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// SignUpAdminBadRequestCode is the HTTP code returned for type SignUpAdminBadRequest
const SignUpAdminBadRequestCode int = 400

/*
SignUpAdminBadRequest Invalid request

swagger:response signUpAdminBadRequest
*/
type SignUpAdminBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSignUpAdminBadRequest creates SignUpAdminBadRequest with default headers values
func NewSignUpAdminBadRequest() *SignUpAdminBadRequest {

	return &SignUpAdminBadRequest{}
}

// WithPayload adds the payload to the sign up admin bad request response
func (o *SignUpAdminBadRequest) WithPayload(payload *models.Error) *SignUpAdminBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the sign up admin bad request response
func (o *SignUpAdminBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SignUpAdminBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SignUpAdminInternalServerErrorCode is the HTTP code returned for type SignUpAdminInternalServerError
const SignUpAdminInternalServerErrorCode int = 500

/*
SignUpAdminInternalServerError Internal server error

swagger:response signUpAdminInternalServerError
*/
type SignUpAdminInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSignUpAdminInternalServerError creates SignUpAdminInternalServerError with default headers values
func NewSignUpAdminInternalServerError() *SignUpAdminInternalServerError {

	return &SignUpAdminInternalServerError{}
}

// WithPayload adds the payload to the sign up admin internal server error response
func (o *SignUpAdminInternalServerError) WithPayload(payload *models.Error) *SignUpAdminInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the sign up admin internal server error response
func (o *SignUpAdminInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SignUpAdminInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
