// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostSearchHandlerFunc turns a function with the right signature into a post search handler
type PostSearchHandlerFunc func(PostSearchParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostSearchHandlerFunc) Handle(params PostSearchParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostSearchHandler interface for that can handle valid post search params
type PostSearchHandler interface {
	Handle(PostSearchParams, interface{}) middleware.Responder
}

// NewPostSearch creates a new http.Handler for the post search operation
func NewPostSearch(ctx *middleware.Context, handler PostSearchHandler) *PostSearch {
	return &PostSearch{Context: ctx, Handler: handler}
}

/*
	PostSearch swagger:route POST /search postSearch

Create a search input
*/
type PostSearch struct {
	Context *middleware.Context
	Handler PostSearchHandler
}

func (o *PostSearch) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostSearchParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
