// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Mercadofarma API
//
//	Find the best price for your medicine
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 1.0.0
//	Contact: Eddie Daniel Riascos Gomez<eddiedanielriascosgomez@gmail.com>
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
