// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Find the best price for your medicine",
    "title": "Mercadofarma API",
    "contact": {
      "name": "Eddie Riascos",
      "email": "eddiedanielriascosgomez@gmail.com"
    },
    "version": "1.0.0"
  },
  "paths": {
    "/search": {
      "post": {
        "security": [
          {
            "sso-jwt": []
          }
        ],
        "description": "Create a search input",
        "parameters": [
          {
            "name": "SearchInput",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/SearchInput"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "A search input created",
            "schema": {
              "$ref": "#/definitions/SearchInputResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "SearchInput": {
      "type": "object",
      "properties": {
        "city": {
          "description": "city name",
          "type": "string",
          "enum": [
            "Cali",
            "Bogota",
            "Medellin",
            "Barranquilla"
          ]
        },
        "country": {
          "description": "country name",
          "type": "string",
          "enum": [
            "CO"
          ]
        },
        "query": {
          "description": "product name",
          "type": "string"
        }
      }
    },
    "SearchInputResponse": {
      "description": "Search Input response",
      "type": "object",
      "properties": {
        "searchInputId": {
          "type": "string"
        }
      },
      "example": {
        "searchInputId": "be16910858a41fd19ea5c1b4e9decca9a784d1024cb00b2158defe2f29dc86dd"
      }
    }
  },
  "securityDefinitions": {
    "sso-jwt": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  },
  "security": [
    {
      "sso-jwt": []
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Find the best price for your medicine",
    "title": "Mercadofarma API",
    "contact": {
      "name": "Eddie Riascos",
      "email": "eddiedanielriascosgomez@gmail.com"
    },
    "version": "1.0.0"
  },
  "paths": {
    "/search": {
      "post": {
        "security": [
          {
            "sso-jwt": []
          }
        ],
        "description": "Create a search input",
        "parameters": [
          {
            "name": "SearchInput",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/SearchInput"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "A search input created",
            "schema": {
              "$ref": "#/definitions/SearchInputResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "SearchInput": {
      "type": "object",
      "properties": {
        "city": {
          "description": "city name",
          "type": "string",
          "enum": [
            "Cali",
            "Bogota",
            "Medellin",
            "Barranquilla"
          ]
        },
        "country": {
          "description": "country name",
          "type": "string",
          "enum": [
            "CO"
          ]
        },
        "query": {
          "description": "product name",
          "type": "string"
        }
      }
    },
    "SearchInputResponse": {
      "description": "Search Input response",
      "type": "object",
      "properties": {
        "searchInputId": {
          "type": "string"
        }
      },
      "example": {
        "searchInputId": "be16910858a41fd19ea5c1b4e9decca9a784d1024cb00b2158defe2f29dc86dd"
      }
    }
  },
  "securityDefinitions": {
    "sso-jwt": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  },
  "security": [
    {
      "sso-jwt": []
    }
  ]
}`))
}
