// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Find the best price for your medicine",
    "title": "Mercadofarma API",
    "contact": {
      "name": "Eddie Daniel Riascos Gomez",
      "email": "eddiedanielriascosgomez@gmail.com"
    },
    "version": "1.0.0"
  },
  "paths": {
    "/v1/admin/signup": {
      "post": {
        "description": "Sign up for business.",
        "tags": [
          "business"
        ],
        "summary": "Sign up for business.",
        "operationId": "signUpAdmin",
        "parameters": [
          {
            "description": "SignUpAdminRequest",
            "name": "SignUpAdminRequest",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/SignUpAdminRequest"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "No content"
          },
          "400": {
            "description": "Invalid request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "BusinessOpeningHour": {
      "properties": {
        "day": {
          "type": "string",
          "enum": [
            "monday",
            "tuesday",
            "wednesday",
            "thursday",
            "friday",
            "saturday",
            "sunday"
          ]
        },
        "endingTime": {
          "type": "string"
        },
        "startTime": {
          "type": "string"
        }
      }
    },
    "Error": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "SignUpAdminRequest": {
      "type": "object",
      "properties": {
        "address": {
          "type": "string"
        },
        "businessName": {
          "type": "string"
        },
        "businessOpeningHours": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/BusinessOpeningHour"
          }
        },
        "businessType": {
          "type": "string",
          "enum": [
            "FARMACIA",
            "TIENDA_NATURISTA",
            "TIENDA_COSMETICA",
            "OTRO"
          ]
        },
        "email": {
          "type": "string",
          "format": "email"
        },
        "firstName": {
          "type": "string"
        },
        "lastName": {
          "type": "string"
        },
        "password": {
          "type": "string",
          "minLength": 8
        },
        "phoneNumber": {
          "type": "string"
        },
        "role": {
          "type": "string",
          "default": "admin"
        },
        "sectorId": {
          "type": "string"
        },
        "taxId": {
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "sso-jwt": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Find the best price for your medicine",
    "title": "Mercadofarma API",
    "contact": {
      "name": "Eddie Daniel Riascos Gomez",
      "email": "eddiedanielriascosgomez@gmail.com"
    },
    "version": "1.0.0"
  },
  "paths": {
    "/v1/admin/signup": {
      "post": {
        "description": "Sign up for business.",
        "tags": [
          "business"
        ],
        "summary": "Sign up for business.",
        "operationId": "signUpAdmin",
        "parameters": [
          {
            "description": "SignUpAdminRequest",
            "name": "SignUpAdminRequest",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/SignUpAdminRequest"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "No content"
          },
          "400": {
            "description": "Invalid request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "BusinessOpeningHour": {
      "properties": {
        "day": {
          "type": "string",
          "enum": [
            "monday",
            "tuesday",
            "wednesday",
            "thursday",
            "friday",
            "saturday",
            "sunday"
          ]
        },
        "endingTime": {
          "type": "string"
        },
        "startTime": {
          "type": "string"
        }
      }
    },
    "Error": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "SignUpAdminRequest": {
      "type": "object",
      "properties": {
        "address": {
          "type": "string"
        },
        "businessName": {
          "type": "string"
        },
        "businessOpeningHours": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/BusinessOpeningHour"
          }
        },
        "businessType": {
          "type": "string",
          "enum": [
            "FARMACIA",
            "TIENDA_NATURISTA",
            "TIENDA_COSMETICA",
            "OTRO"
          ]
        },
        "email": {
          "type": "string",
          "format": "email"
        },
        "firstName": {
          "type": "string"
        },
        "lastName": {
          "type": "string"
        },
        "password": {
          "type": "string",
          "minLength": 8
        },
        "phoneNumber": {
          "type": "string"
        },
        "role": {
          "type": "string",
          "default": "admin"
        },
        "sectorId": {
          "type": "string"
        },
        "taxId": {
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "sso-jwt": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  }
}`))
}
