// Code generated by MockGen. DO NOT EDIT.
// Source: details.go

// Package mock_details is a generated GoMock package.
package mock_details

import (
	context "context"
	reflect "reflect"

	core "github.com/mercadofarma/services/core"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// InsertDetail mocks base method.
func (m *MockService) InsertDetail(ctx context.Context, detail *core.Detail) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertDetail", ctx, detail)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertDetail indicates an expected call of InsertDetail.
func (mr *MockServiceMockRecorder) InsertDetail(ctx, detail interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertDetail", reflect.TypeOf((*MockService)(nil).InsertDetail), ctx, detail)
}
